import { OW_W, OW_H } from "../systems/map.js";
const S = {
  root: { minHeight: "100vh", background: "radial-gradient(ellipse at top, #1a1830, #0c0b16 60%)", color: "#e8e6f0", fontFamily: "'Georgia', serif" },
  header: { flex: "0 0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, flexWrap: "nowrap", padding: "8px 14px", borderBottom: "1px solid #232136", position: "sticky", top: 0, background: "#0c0b16ee", backdropFilter: "blur(8px)", zIndex: 10 },
  logo: { fontWeight: 800, letterSpacing: 2, fontSize: 18, cursor: "pointer", fontFamily: "'Courier New', monospace" },
  nav: { display: "flex", gap: 6, flexWrap: "wrap", justifyContent: "flex-end", flex: "1 1 auto" },
  navBtn: { background: "transparent", color: "#b8b4d0", border: "1px solid #2c2a40", padding: "6px 12px", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontSize: 13, whiteSpace: "nowrap" },
  navBtnActive: { background: "#ffd34d", color: "#15101f", borderColor: "#ffd34d", fontWeight: 800 },
  floorTag: { fontFamily: "monospace", color: "#ffd34d", letterSpacing: 2 },
  main: { maxWidth: 960, margin: "0 auto", padding: "20px 16px 96px" },
  tabBar: { position: "fixed", bottom: 0, left: 0, right: 0, display: "flex", justifyContent: "space-between", alignItems: "stretch", background: "#0c0b16f2", borderTop: "1px solid #232136", backdropFilter: "blur(8px)", zIndex: 40, paddingBottom: "env(safe-area-inset-bottom, 0px)", overflowX: "auto" },
  tab: { flex: "1 1 0", minWidth: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 2, background: "transparent", border: "none", color: "#8a86a8", padding: "8px 1px", cursor: "pointer", fontFamily: "inherit", borderTop: "2px solid transparent" },
  tabActive: { color: "#ffd34d", borderTop: "2px solid #ffd34d", background: "#ffd34d12" },
  toast: { position: "fixed", top: 70, left: "50%", transform: "translateX(-50%)", background: "#ffd34d", color: "#111", padding: "10px 18px", borderRadius: 10, fontWeight: 700, zIndex: 50, boxShadow: "0 6px 24px #0008" },

  title: { textAlign: "center", paddingTop: 30 },
  h1: { fontSize: 52, margin: "10px 0 6px", letterSpacing: 4, fontFamily: "'Courier New', monospace" },
  tagline: { maxWidth: 560, margin: "0 auto 26px", opacity: 0.7, lineHeight: 1.6 },
  bigBtn: { background: "linear-gradient(135deg,#ffd34d,#ff9a3d)", color: "#1a1208", border: "none", padding: "13px 26px", borderRadius: 12, fontWeight: 800, fontSize: 16, cursor: "pointer", marginTop: 14, fontFamily: "inherit", boxShadow: "0 6px 20px #ffae3344" },
  ghostBtn: { background: "transparent", color: "#b8b4d0", border: "1px solid #2c2a40", padding: "13px 22px", borderRadius: 12, cursor: "pointer", marginTop: 14, fontFamily: "inherit", fontSize: 15 },
  featRow: { display: "flex", gap: 14, justifyContent: "center", flexWrap: "wrap", marginTop: 40 },
  feat: { width: 150, display: "flex", flexDirection: "column", gap: 4, alignItems: "center", textAlign: "center", padding: 14, border: "1px solid #232136", borderRadius: 12, background: "#15132410" },

  sectionHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 16, marginBottom: 18, flexWrap: "wrap" },
  h2: { fontSize: 28, margin: "0 0 4px", fontFamily: "'Courier New', monospace", letterSpacing: 1 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(130px,1fr))", gap: 12 },
  monCard: { position: "relative", background: "#15132e", border: "2px solid #262633", borderRadius: 14, padding: 12, textAlign: "center", cursor: "pointer", transition: "transform .12s, border-color .12s", display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  teamBadge: { position: "absolute", top: 6, right: 6, width: 22, height: 22, borderRadius: "50%", background: "#7ee787", color: "#111", display: "grid", placeItems: "center", fontWeight: 800, fontSize: 12 },
  elementPill: { fontSize: 10, fontWeight: 700, color: "#1a1208", padding: "1px 8px", borderRadius: 20, textTransform: "uppercase", letterSpacing: 1, marginTop: 4 },

  panel: { maxWidth: 600, margin: "0 auto", background: "#15132e", border: "1px solid #262633", borderRadius: 16, padding: 26 },
  textarea: { width: "100%", boxSizing: "border-box", background: "#0c0b16", color: "#e8e6f0", border: "1px solid #2c2a40", borderRadius: 10, padding: 12, fontFamily: "inherit", fontSize: 15, resize: "vertical", marginBottom: 12 },
  forgeAnim: { marginTop: 16, opacity: 0.7, fontStyle: "italic" },
  errorBox: { background: "#ff5a4d22", border: "1px solid #ff5a4d", color: "#ffb4ad", fontSize: 13, padding: "8px 12px", borderRadius: 8, marginBottom: 10 },

  fuseStage: { display: "flex", alignItems: "center", justifyContent: "center", gap: 14, margin: "20px 0", flexWrap: "wrap" },
  fuseSlot: { width: 96, height: 110, border: "2px solid #2c2a40", borderRadius: 14, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", background: "#15132e" },

  battle: { maxWidth: 720, margin: "0 auto", position: "relative" },
  battleLogTight: {},
  enemyZone: { display: "flex", justifyContent: "center", marginBottom: 6 },
  enemyCard: { position: "relative", textAlign: "center", background: "#1a1530", border: "1px solid #3a2a40", borderRadius: 16, padding: "8px 16px", minWidth: 0 },
  intent: { position: "absolute", top: -12, left: "50%", transform: "translateX(-50%)", background: "#ff5a4d", color: "#fff", padding: "3px 12px", borderRadius: 20, fontWeight: 800, fontSize: 13, fontFamily: "monospace" },
  log: { height: 38, overflow: "hidden", display: "flex", flexDirection: "column", justifyContent: "flex-end", fontSize: 11, fontFamily: "monospace", color: "#9a96b8", margin: "4px 0", padding: "0 8px" },
  activeFighter: { display: "flex", alignItems: "center", gap: 10, background: "#15132e", border: "1px solid #262633", borderRadius: 14, padding: "6px 12px" },
  activeArt: { borderRadius: 10, border: "2px solid", padding: 2, background: "#0c0b16", flexShrink: 0 },
  benchRow: { display: "flex", gap: 8, justifyContent: "center", marginTop: 10, flexWrap: "wrap" },
  benchMon: { position: "relative", display: "flex", flexDirection: "column", alignItems: "center", gap: 1, background: "#15132e", border: "2px solid #2c2a40", borderRadius: 12, padding: "6px 10px", color: "#e8e6f0", fontFamily: "inherit", minWidth: 60 },
  activeTag: { fontSize: 8, background: "#7ee787", color: "#0c0b16", padding: "0 5px", borderRadius: 5, fontWeight: 800, textTransform: "uppercase", marginTop: 1 },
  energy: { display: "flex", flexDirection: "column", alignItems: "center", gap: 6 },
  energyOrb: { background: "radial-gradient(circle,#ffd34d,#ff9a3d)", color: "#1a1208", width: 48, height: 48, borderRadius: "50%", display: "grid", placeItems: "center", fontWeight: 800, fontFamily: "monospace" },
  endBtn: { background: "#2c2a40", color: "#e8e6f0", border: "none", padding: "6px 12px", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontSize: 12 },

  hand: { display: "flex", gap: 6, justifyContent: "center", flexWrap: "nowrap", marginTop: 4, overflowX: "auto", paddingBottom: 2 },
  playCard: { width: 90, flex: "0 0 auto", background: "linear-gradient(160deg,#1c1838,#15122a)", border: "2px solid #ffd34d", borderRadius: 11, padding: "6px 7px 7px", position: "relative", transition: "transform .12s", boxShadow: "0 4px 14px #0006" },
  cardCost: { position: "absolute", top: -9, left: -7, width: 22, height: 22, borderRadius: "50%", display: "grid", placeItems: "center", fontWeight: 800, fontSize: 12, color: "#1a1208", fontFamily: "monospace", border: "2px solid #15122a" },
  cardType: { fontSize: 9, textTransform: "uppercase", letterSpacing: 1, opacity: 0.5, textAlign: "right" },
  cardName: { fontWeight: 800, fontSize: 11, margin: "1px 0 3px", lineHeight: 1.05 },
  cardText: { fontSize: 9, lineHeight: 1.25, opacity: 0.82, maxHeight: 46, overflow: "hidden" },
  cardOwner: { fontSize: 9, opacity: 0.45, marginTop: 6, fontStyle: "italic" },
  deckInfo: { textAlign: "center", fontSize: 12, opacity: 0.5, marginTop: 10, fontFamily: "monospace" },

  barOuter: { position: "relative", height: 18, background: "#0c0b16", borderRadius: 20, overflow: "hidden", border: "1px solid #2c2a40", marginTop: 6 },
  barInner: { height: "100%", transition: "width .35s", borderRadius: 20 },
  barLabel: { position: "absolute", inset: 0, display: "grid", placeItems: "center", fontSize: 11, fontWeight: 700, fontFamily: "monospace", textShadow: "0 1px 2px #000" },
  statusRow: { display: "flex", gap: 6, justifyContent: "center", marginTop: 4, minHeight: 18 },
  statBlock: { fontSize: 11, background: "#3fa9f533", padding: "1px 7px", borderRadius: 10 },
  statShield: { fontSize: 11, background: "#a571ff44", color: "#d4b8ff", padding: "1px 7px", borderRadius: 10, fontWeight: 700 },
  statRegen: { fontSize: 11, background: "#7ee78733", padding: "1px 7px", borderRadius: 10 },
  statVuln: { fontSize: 11, background: "#ff8a4d44", padding: "1px 7px", borderRadius: 10 },
  statPoison: { fontSize: 11, background: "#9bd13a44", color: "#c8f06a", padding: "1px 7px", borderRadius: 10 },
  statChill: { fontSize: 11, background: "#9fe6ff33", color: "#cdf2ff", padding: "1px 7px", borderRadius: 10 },
  statSoak: { fontSize: 11, background: "#3fa9f544", color: "#bfe4ff", padding: "1px 7px", borderRadius: 10 },
  statShock: { fontSize: 11, background: "#ffe14d44", color: "#fff0a0", padding: "1px 7px", borderRadius: 10 },
  statDecay: { fontSize: 11, background: "#6b5a8a55", color: "#cabbe0", padding: "1px 7px", borderRadius: 10 },
  reactionFlash: { marginTop: 4, fontSize: 12, fontWeight: 800, color: "#ffd34d", letterSpacing: 1 },
  statSyn: { fontSize: 11, background: "#ffd34d33", color: "#ffd34d", padding: "1px 7px", borderRadius: 10, fontWeight: 700 },
  matchGood: { fontSize: 11, color: "#7ee787", fontWeight: 700, marginTop: 4 },
  matchBad: { fontSize: 11, color: "#ff8a8a", fontWeight: 700, marginTop: 4 },
  cardTags: { display: "flex", gap: 4, flexWrap: "wrap", marginTop: 2, minHeight: 14 },
  cardTagRetain: { fontSize: 8, background: "#5fd0e033", color: "#5fd0e0", padding: "0 5px", borderRadius: 5, fontWeight: 700, textTransform: "uppercase" },
  cardTagExhaust: { fontSize: 8, background: "#ff5a4d33", color: "#ff8a8a", padding: "0 5px", borderRadius: 5, fontWeight: 700, textTransform: "uppercase" },
  statBurn: { fontSize: 11, background: "#ff5a4d33", padding: "1px 7px", borderRadius: 10 },
  statWeak: { fontSize: 11, background: "#3fa9f533", padding: "1px 7px", borderRadius: 10 },
  statStr: { fontSize: 11, background: "#ffd34d33", padding: "1px 7px", borderRadius: 10 },

  overlay: { position: "absolute", inset: 0, background: "#0c0b16dd", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 16, zIndex: 5 },

  rewardRow: { display: "flex", gap: 14, flexWrap: "wrap", marginTop: 16 },
  rewardCard: { flex: "1 1 160px", background: "#1a1530", border: "1px solid #3a2a40", borderRadius: 14, padding: 18, textAlign: "center", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, transition: "border-color .12s" },
  rewardDesc: { fontSize: 12, opacity: 0.6 },

  mapScroll: { maxHeight: "62vh", overflowY: "auto", border: "1px solid #232136", borderRadius: 14, padding: "10px 6px", background: "linear-gradient(180deg,#120f20,#0c0b16)" },
  mapInner: { display: "flex", flexDirection: "column", gap: 14 },
  mapRow: { display: "flex", alignItems: "center", gap: 8 },
  mapRowLabel: { width: 42, flexShrink: 0, fontFamily: "monospace", fontSize: 10, color: "#6a6688", textAlign: "right" },
  mapNodes: { display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap", flex: 1 },
  mapNode: { position: "relative", width: 64, height: 64, borderRadius: 14, border: "2px solid", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 2, color: "#e8e6f0", fontFamily: "inherit" },
  pickHint: { position: "absolute", bottom: -8, fontSize: 8, background: "#ffd34d", color: "#15101f", padding: "0 5px", borderRadius: 5, fontWeight: 800, textTransform: "uppercase" },
  legend: { display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "center", marginTop: 12 },

  buyBtn: { marginTop: 6, background: "#ffd34d", color: "#15101f", border: "none", borderRadius: 8, padding: "5px 10px", fontWeight: 800, fontFamily: "inherit", fontSize: 13 },
  mysteryBtn: { background: "#1a1530", color: "#e8e6f0", border: "1px solid #a571ff66", borderRadius: 10, padding: "12px 14px", cursor: "pointer", fontFamily: "inherit", fontSize: 14, textAlign: "left" },
  cheatBtn: { background: "#2c2a40", color: "#ffd34d", border: "1px solid #ffd34d55", borderRadius: 8, padding: "8px 14px", cursor: "pointer", fontFamily: "inherit", fontSize: 13, fontWeight: 700 },
  versionTag: { fontSize: 9, color: "#7ee787", fontWeight: 700, marginLeft: 6, opacity: 0.85, letterSpacing: 1, verticalAlign: "middle" },
  adminRow: { background: "#15132e", border: "1px solid #2c2a40", borderRadius: 10, padding: "8px 10px", marginBottom: 6, cursor: "pointer" },
  adminLabel: { fontSize: 9, textTransform: "uppercase", letterSpacing: 1, color: "#ffd34d", opacity: 0.8, marginBottom: 2 },
  dropsBar: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center", margin: "6px 0 12px", fontSize: 12 },
  dropPill: { background: "#15132e", border: "1px solid #2c2a40", borderRadius: 14, padding: "3px 10px", fontSize: 11, whiteSpace: "nowrap" },
  dexSelect: { background: "#15132e", color: "#e8e6f0", border: "1px solid #2c2a40", borderRadius: 8, padding: "8px 10px", fontFamily: "inherit", fontSize: 12 },

  owWrap: { border: "2px solid #232136", borderRadius: 12, overflow: "hidden", background: "#0c0b16" },
  owGrid: { display: "grid", gap: 0, width: "100%", aspectRatio: `${OW_W} / ${OW_H}` },
  owTile: { position: "relative", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "inset 0 0 0 0.5px #0003" },
  owFeature: { fontSize: "min(5vw,30px)", lineHeight: 1 },
  owPlayer: { position: "absolute", fontSize: "min(5vw,30px)", lineHeight: 1, filter: "drop-shadow(0 1px 2px #000)" },
  owStanding: { textAlign: "center", fontSize: 13, opacity: 0.8, margin: "10px 0", padding: "8px", background: "#15132e", borderRadius: 8 },
  dpad: { display: "grid", gridTemplateColumns: "repeat(3, 54px)", gridTemplateRows: "repeat(3, 54px)", gap: 6, justifyContent: "center", margin: "14px 0" },
  dBtn: { background: "#2c2a40", color: "#ffd34d", border: "1px solid #3a3850", borderRadius: 10, fontSize: 22, cursor: "pointer", fontFamily: "inherit", display: "flex", alignItems: "center", justifyContent: "center" },

  viewBtn: { marginTop: 6, background: "transparent", color: "#9a96b8", border: "1px solid #2c2a40", borderRadius: 8, padding: "3px 10px", fontSize: 11, cursor: "pointer", fontFamily: "inherit" },
  evoDot: { position: "absolute", top: 6, left: 6, width: 20, height: 20, borderRadius: "50%", background: "#7ee787", color: "#0c0b16", display: "grid", placeItems: "center", fontWeight: 800, fontSize: 12 },
  modalBackdrop: { position: "fixed", inset: 0, background: "#06050ccc", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 20, overflowY: "auto" },
  moveList: { display: "flex", flexDirection: "column", gap: 6, maxWidth: 300, width: "100%" },
  moveChip: { background: "#15132e", border: "1px solid", borderRadius: 8, padding: "6px 10px", fontSize: 13 },

  codexElementHead: { fontFamily: "'Courier New', monospace", fontWeight: 800, letterSpacing: 2, fontSize: 15, marginBottom: 8, borderBottom: "1px solid #232136", paddingBottom: 4 },
  codexGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(110px,1fr))", gap: 10 },
  codexCard: { position: "relative", background: "#15132e", border: "1px solid", borderRadius: 12, padding: 10, textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", gap: 2, minHeight: 96, justifyContent: "center" },
  ownedTag: { position: "absolute", top: 4, right: 4, fontSize: 8, background: "#7ee787", color: "#0c0b16", padding: "1px 5px", borderRadius: 6, fontWeight: 800, textTransform: "uppercase" },
  seenTag: { position: "absolute", top: 4, right: 4, fontSize: 8, background: "#5fd0e0", color: "#0c0b16", padding: "1px 5px", borderRadius: 6, fontWeight: 800, textTransform: "uppercase" },
  evoPanel: { width: "100%", maxWidth: 300, background: "#15132e", border: "1px solid #2c2a40", borderRadius: 12, padding: 12 },
  evoReq: { display: "flex", gap: 8, alignItems: "center", fontSize: 12, padding: "3px 0" },
  codexInfoRow: { display: "flex", justifyContent: "space-between", fontSize: 13, padding: "4px 10px", background: "#15132e", borderRadius: 8 },
  lockedMoves: { width: "100%", maxWidth: 300, textAlign: "center", fontSize: 12, opacity: 0.6, fontStyle: "italic", padding: "12px", border: "1px dashed #2c2a40", borderRadius: 10 },

  wheelRow: { display: "flex", gap: 8, justifyContent: "center", flexWrap: "wrap", margin: "18px 0" },
  wheel: { display: "flex", flexDirection: "column", alignItems: "center", gap: 4, width: 78 },
  wheelFace: { width: "100%", minHeight: 52, borderRadius: 12, border: "2px solid", display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center", fontWeight: 800, fontSize: 12, padding: "4px 2px", background: "#15132e", transition: "transform .1s" },
  rollSummary: { textAlign: "center", display: "flex", flexDirection: "column", gap: 4, margin: "8px 0 16px", padding: 12, background: "#15132e", border: "1px solid #2c2a40", borderRadius: 12 },

  bagSub: { fontFamily: "'Courier New', monospace", letterSpacing: 1, marginTop: 22, marginBottom: 8, color: "#b8b4d0" },
  codexTabs: { display: "flex", gap: 6, marginBottom: 16, flexWrap: "wrap" },
  codexTab: { background: "transparent", color: "#b8b4d0", border: "1px solid #2c2a40", borderRadius: 8, padding: "6px 14px", cursor: "pointer", fontFamily: "inherit", fontSize: 13, fontWeight: 700 },
  codexTabActive: { background: "#ffd34d", color: "#15101f", borderColor: "#ffd34d" },
  mechCard: { background: "#15132e", border: "1px solid #2c2a40", borderRadius: 12, padding: "12px 14px", marginBottom: 10 },
  mechTitle: { fontWeight: 800, fontSize: 14, marginBottom: 4 },
  mechBody: { fontSize: 12.5, lineHeight: 1.5, opacity: 0.82 },
  itemGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(160px,1fr))", gap: 10 },
  itemTile: { background: "#15132e", border: "1px solid", borderRadius: 12, padding: 12, display: "flex", flexDirection: "column", gap: 3 },
  potionBar: { display: "flex", gap: 8, justifyContent: "center", marginTop: 12, flexWrap: "wrap" },
  consumeBar: { display: "flex", gap: 5, justifyContent: "center", flexWrap: "nowrap", overflowX: "auto", margin: "0 0 4px", padding: "0 2px" },
  consumeBtn: { position: "relative", flex: "0 0 auto", display: "grid", placeItems: "center", width: 34, height: 34, background: "#1a1530", border: "1px solid #3a2a40", borderRadius: 9, cursor: "pointer", color: "#e8e6f0", fontFamily: "inherit" },
  consumeCount: { position: "absolute", bottom: -3, right: -3, background: "#2c2a40", borderRadius: 8, fontSize: 8, padding: "0 3px", fontWeight: 700 },
  potionBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, background: "#1a1530", border: "1px solid #3a2a40", borderRadius: 10, padding: "6px 10px", cursor: "pointer", color: "#e8e6f0", fontFamily: "inherit" },
};

// ---- TCG card frame styling ----
const tcg = {
  card: {
    position: "relative",
    borderRadius: 18,
    padding: 7,
    background: "linear-gradient(145deg,#2a2238,#14101f 55%,#221a30)",
    boxShadow: "0 14px 40px #000a, inset 0 1px 0 #ffffff14",
    overflow: "hidden",
    fontFamily: "'Georgia', serif",
  },
  sheen: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(115deg, transparent 30%, #ffffff14 45%, transparent 60%)",
    pointerEvents: "none",
    zIndex: 3,
  },
  border: {
    position: "relative",
    height: "100%",
    border: "2px solid",
    borderRadius: 13,
    padding: 8,
    display: "flex",
    flexDirection: "column",
    gap: 7,
    background: "linear-gradient(160deg,#171225,#0e0a17)",
  },
  titleBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    background: "linear-gradient(90deg,#ffffff10,transparent)",
    borderRadius: 8,
    padding: "3px 6px",
  },
  name: {
    fontWeight: 800,
    fontSize: 15,
    letterSpacing: 0.4,
    textShadow: "0 1px 2px #000",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  elementGem: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    fontSize: 13,
    color: "#15101f",
    flexShrink: 0,
    boxShadow: "0 0 8px var(--accent), inset 0 1px 2px #fff8",
  },
  artWindow: {
    position: "relative",
    flex: "0 0 48%",
    borderRadius: 8,
    overflow: "hidden",
    background: "#0c0b16",
  },
  hpBadge: {
    position: "absolute",
    bottom: 5,
    right: 5,
    color: "#15101f",
    fontWeight: 800,
    fontSize: 14,
    padding: "1px 9px",
    borderRadius: 20,
    boxShadow: "0 2px 6px #0008",
  },
  corner: {
    position: "absolute",
    width: 14,
    height: 14,
    borderTop: "2px solid",
    borderLeft: "2px solid",
    borderTopLeftRadius: 6,
    opacity: 0.8,
  },
  typeLine: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 2px",
  },
  elementPillSm: {
    fontSize: 10,
    fontWeight: 800,
    color: "#15101f",
    padding: "2px 10px",
    borderRadius: 20,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  descBox: {
    flex: 1,
    background: "linear-gradient(180deg,#ffffff0a,#00000030)",
    border: "1px solid #ffffff14",
    borderRadius: 8,
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
  },
  descText: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.45,
    fontStyle: "italic",
    color: "#d8d3ea",
    flex: 1,
  },
  cardCount: {
    fontSize: 10,
    opacity: 0.55,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 6,
    textAlign: "right",
  },
  footer: { marginTop: 2 },
};

const CSS = `
@keyframes floatUp { from { transform: translateY(0); opacity: 1; } to { transform: translateY(-46px); opacity: 0; } }
.floatie { animation: floatUp 0.9s ease-out forwards; }
@keyframes shakeX { 0%,100% { transform: translateX(0); } 20% { transform: translateX(-6px); } 40% { transform: translateX(5px); } 60% { transform: translateX(-4px); } 80% { transform: translateX(3px); } }
.shake { animation: shakeX 0.32s ease; }
.card:active { transform: scale(0.94); }

  * { box-sizing: border-box; }
  body { margin: 0; padding: 0; }
  .card:hover { transform: translateY(-10px) scale(1.04); }
  .monCard:hover { transform: translateY(-3px); }
  .float { animation: float 3s ease-in-out infinite; }
  @keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-12px)} }
  .pulse { animation: pulse 1.2s ease-in-out infinite; }
  @keyframes pulse { 0%,100%{opacity:.5} 50%{opacity:1} }
  button:disabled { opacity:.4; cursor:not-allowed; }
  textarea:focus { outline: 1px solid #ffd34d; }
  div[style*="rewardCard"]:hover { border-color:#ffd34d !important; }
`;

export { S, tcg, CSS };
