"""Scan public/art/sprites/*.png and emit src/data/sprites.json — the manifest the
combat-v2 3D board reads to place backgroundless billboard sprites.

Each entry carries the natural pixel size so a react-three-fiber plane can be sized
to the sprite's true aspect ratio (billboards must not stretch). Run after baking
new sprites:  python3 scripts/gen_sprite_manifest.py
"""
import os, json, glob
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITE_DIR = os.path.join(ROOT, "public/art/sprites")
OUT = os.path.join(ROOT, "src/data/sprites.json")

# id -> kind/anchor metadata. anchor "bottom" = the sprite stands on the ground
# (billboard pivots at its base). Extend as new sprite families are added.
KIND = {"tree": "environment"}


def kind_of(sprite_id):
    head = sprite_id.split("-", 1)[0]
    return "tree" if head == "tree" else head


def main():
    entries = []
    for path in sorted(glob.glob(os.path.join(SPRITE_DIR, "*.png"))):
        sid = os.path.splitext(os.path.basename(path))[0]
        with Image.open(path) as im:
            w, h = im.size
        entries.append({
            "id": sid,
            "file": f"art/sprites/{sid}.png",   # relative to Vite BASE
            "kind": kind_of(sid),
            "w": w, "h": h,
            "aspect": round(w / h, 4),
            "anchor": "bottom",                  # billboard pivots at the base
        })
    manifest = {"note": "Backgroundless billboard sprites for the combat-v2 3D board. w/h are natural px; size planes by aspect. Generated by scripts/gen_sprite_manifest.py.",
                "sprites": entries}
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(f"wrote {OUT} with {len(entries)} sprites")
    for e in entries:
        print(f"  {e['id']:16} {e['w']}x{e['h']}  aspect {e['aspect']}")


if __name__ == "__main__":
    main()
